version: '2'
#networks:
#  my-network:
#    driver: bridge
services:
  influxdb:
    image: bitnami/influxdb:latest
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_USER=dbuser
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_DB=my_database
      - INFLUXDB_USER_BUCKET=mybucket
      - INFLUXDB_USER_ORG=my_org
    volumes:
      - influxdb_data:/bitnami/influxdb
  dashboard:
    image: bitnami/grafana:latest
    ports:
      - "3000:3000"
    environment:
    #  GF_SECURITY_ADMIN_PASSWORD: "bitnami"
    #  GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8080/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
    volumes:
      - grafana_data:/opt/bitnami/grafana/data
  telegraf:
    image: telegraf:latest
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
  low_voltage:
    image: ghcr.io/cms-tedd-ip2i/low_voltage:0.0.1 
    restart: always
    stdin_open: true #docker run -i
    tty: true #docker run -t
    links:
      - mosquitto
    #command: ["python3", "hmp.py", "lw_volt", "mosquitto"]
    volumes:
      - low_voltage:/usr/app/low_voltage/
  web_server:
    image: ghcr.io/cms-tedd-ip2i/tracker_dcs_web:0.0.2
    restart: always
    #stdin_open: true
    #tty: true
    # port must be open even in production as it's a webserver open to outside
    # TODO: setup authentication
    environment:
      - APP_USER=cdozen
      - APP_PASSWORD=test
    ports:
      - "8001:8000"
    expose:
      - "8001"
    links:
      - mosquitto
    command: ["uvicorn", "tracker_dcs_web.web_server.app:app", "--host", "0.0.0.0"]
    volumes:
      - web_server:/code

volumes:
  influxdb_data:
  grafana_data:
  mosquitto_data:
  mosquitto_log:
  web_server:
  low_voltage:

