version: "3"
services:
  hv:
    image: ghcr.io/cms-tedd-ip2i/dummy:0.0.1
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'hv', 'mosquitto']
  lv:
    image: ghcr.io/cms-tedd-ip2i/dummy:0.0.1
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'lv', 'mosquitto']
  sensor_1:
    image: ghcr.io/cms-tedd-ip2i/dummy:0.0.1
    links:
      - mosquitto
    command: ['python', 'dummy/sensor.py', 'sensor_1', 'mosquitto']
  
  #low_voltage:
  #  image: ghcr.io/cms-tedd-ip2i/low_voltage:0.0.1
  #  links:
  #    - mosquitto
  #  command: ['python3', 'hmp.py', 'lw_volt', 'mosquitto']
  


















  
 


